import os
import argparse
import struct
import numpy as np
from NGlib import post as ngpost
from pathlib import Path

__doc__ = 'package with routines to work with output files generated by Fortran \
BLseparation code'

def readflow(fnm : str | Path,readnup : bool = True):
    '''
    @brief read variables from flow field

    @details read the fluid variables from a binary file created by BLcode or BLsbcode

        coord,coordm,V,P = readflow(fnm)

    @param fnm      [str] full name of the file
    @param readnup  [bool] read nu_t and pressure

    @param coord    [tuple] (x,y,z) coordinate of the grid vertices
    @param coordm   [tuple] (x,y,z) coordinate of the grid centers
    @param U        [tuple] (u,v,w) velocity vector field
    @param nu_t     [arr]   eddy viscosity
    @param P        [arr]   pressure
    '''

    isz = struct.calcsize('i') # size of int32
    dsz = struct.calcsize('d') # size of float64

    with open(fnm,'rb') as f:

        # time and nu
        _, _ = struct.unpack('>2d',f.read(2*dsz))

        # Coordinates of staggered grid
        coord = []
        for _ in range(3):
            n = struct.unpack('>i',f.read(isz))[0]
            coord.append(struct.unpack(f'>{n}d',f.read(n*dsz)))

        # Coordinates of pressure grid
        coordm = []
        for _ in range(3):
            n = struct.unpack('>i',f.read(isz))[0]
            coordm.append(struct.unpack(f'>{n}d',f.read(n*dsz)))

        vels = []
        # Velocity field and nu_t and pressure
        ind = 3
        if readnup:
            ind += 2
        dummy = [] # init dummy
        for _ in range(ind):
            n = struct.unpack('>3i',f.read(3*isz))
            N = int(np.prod(n)) # just for python type checking

            dummy = struct.unpack(f'>{N}d',f.read(N*dsz))
            vels.append(np.transpose(
                np.reshape(dummy,n[::-1]),(2,1,0))) # flip order in python

        del dummy

    outs = [vels[:3]]
    if readnup:
        outs.append(vels[-2])
        outs.append(vels[-1])

    return coord, coordm, *outs


def saveflow(fnm : str | Path, coord : np.ndarray, coordm : np.ndarray, 
             U : np.ndarray, nu : float, time : float = 0):
    '''
    @brief save variables to flow field

    @details save the fluid variables to a binary file to be read by BLcode or BLsbcode

        readflow(fnm,coord,coordm,V)

    @param fnm      [str] full name of the file
    @param coord    [tuple] (x,y,z) coordinate of the grid vertices
    @param coordm   [tuple] (x,y,z) coordinate of the grid centers
    @param U        [tuple] (u,v,w) velocity vector field

    @param time     [double] start time
    '''

    with open(fnm,'wb') as f:

        # time and nu
        f.write(struct.pack('>d',time))
        f.write(struct.pack('>d',nu))

        # Coordinates of staggered grid and pressure grid
        for cc in (coord,coordm):
            for i in range(3):
                n = len(cc[i])
                f.write(struct.pack('>i',n))
                f.write(struct.pack(f'>{n}d',*cc[i]))

        # Velocity field
        for i in range(3):
            n = U[i].size
            uu = np.transpose(U[i],(2,1,0))
            f.write(struct.pack('>3i',*uu.shape[::-1]))
            f.write(struct.pack(f'>{n}d',*uu.ravel()))


def readstat(fnm,read='all'):
    '''
    @brief read stats file from channel

    @detail
        hdr,data = readstat(fnm,read)

    Read the stats generated by channel

    inputs
        @param fnm      [str] full path name of the file
        @param read     [str] if 'all': read data. Any other value: only header

    outputs
        @param hdr       [np.array] variables of the simulation:
        hdr = [t, Retau, utau, nu, nx_global, ny_global, nz_global, istep]

        @param data      [np.array] statistics of the flow
        data = [y, Umean, U2mean, V2mean, W2mean, UVmean, P2mean]
    '''
    data = None # init empty data
    hdr  = None # init header

    f = open(fnm,'r')
    hdr = np.array(f.readline().split()[1:]).astype(float)

    if read == 'all':
        content = f.readlines()
        data = ngpost.readstrmat(content)

    f.close()

    return hdr,data


class stats:
    '''
    @brief manage variables store in stats files

    @detail Read the friction coefficient and velocity
    statistics from a boundary layer simulation
    
    Usage:
        BLs = stats(nf)
        
        Inputs:
            @param  nf      ngpost.NumberedFile object of the stats file
    

    @methods
        updatedata(ifr) ->  read the content of the ifr frame

        getCf() -> obtain the friction coefficient (and ifr is assumed)

        getvars() -> obtain the velocity stats (and ifr is assumed)

    '''

    def __init__(self,numf : ngpost.NumberedFile):
        '''
        @brief manage variables store in stats files

        @detail Read the friction coefficient and velocity
        statistics from a boundary layer simulation
        
            BLs = stats(nf)
            
            Inputs:
                @param  nf      [ngpost.NumberedFile] object of the stats file
        '''
        self._nf = numf # numbered file object


    def updatedata(self,ifr : int):
        '''
        @brief load the data for the ifr frame

        @details this function loads the data from the ifr in the private variable
        self._content to be used by getCf() and detvars()
            
            self.updatedata(ifr)

            @param ifr  [int] value from the list self._nf.getifrl()

        Values loaded to the object:
            @param  self.nu             [float] viscosity
            @param  self.n[x|y|z]       [int] number of grid points

        '''
        with open(self._nf.getfullfilename(ifr)) as f:
            self._content = f.readlines()

        header = np.array(self._content[0].split()[1:])

        self.nu = header[1].astype(float)
        self.nx,self.ny,self.nz = header[2:-1].astype(int)


    def getCf(self):
        '''
        @brief get the fricion coefficient

        @details store the friction coefficient in self.Cf corresponding to the
        frame ifr. Cf is averaged along the spanwise direction
            
            self.getCf()

        Values loaded to the object:
            @param self.Cf  [np.array size nx] friction coefficient
            @param self.x   [np.array size nx] x position of Cf

        '''
        self.Cf = np.array(self._content[1].split()).astype(float)
        self.x  = np.array(self._content[2].split()).astype(float)


    def getvars(self):
        '''
        @brief get statistics of the velocity

        @details store the velocity and pressure stats 
            
            self.getvars()

        Values loaded to the object:
            @param Um   [np.array 3 x ny x nx] first moment of the 3 vel components
            @param U2m  [np.array 3 x ny x nx] second moment of the 3 vel components
            @param Pm   [np.array ny x nx] first moment of the pressure
            @param P2m  [np.array ny x nx] second moment of the pressure

            @param x    [np.array nx] x-coordinate
            @param y    [np.array ny] y-coordinate

        '''

        self.x = np.array(self._content[2].split()).astype(float)

        data = ngpost.readstrmat(self._content[3:])

        self.y = data[:,0]

        var = []
        for ii in range(8):
            i0 = 1 + ii*self.nx
            var.append(data[:,i0:self.nx+i0])

        self.Um = np.array(var[:3])
        self.U2m = np.array(var[3:6])
        self.Pm = np.array(var[6])
        self.P2m = np.array(var[7])


def vorticity_z ( xc : np.ndarray, yc : np.ndarray, u : np.ndarray, v : np.ndarray ) \
        -> np.ndarray:
    '''@brief compute the vorticity in the z-direction

    @details: The stat files save ux and uy in the cell centers. To compute the 
    vorticity we use central differences:
        du_dy[i] = (u[i+1] - u[i-1]) / ( y[i+1] - y[i-1] )

        wz = vorticity_z( x, y, u, v )

    Parameters:
        @param  x       [np.array Nx] x-coordinate of at the cell center

        @param  y       [np.array Ny] y-coordinate of at the cell center

        @param  u       [np.array Ny x Ny ] horizontal velocity at cell center

        @param  v       [np.array Ny x Ny ] vertical velocity at cell center

    Returns
        @param  wz      [np.array (Ny-1) x (Nx -1)] vorticity at inner cell centers
    '''
    
    dudy = (u[2:,1:-1] - u[:-2,1:-1]) / (yc[2:,np.newaxis] - yc[:-2,np.newaxis])
    dvdx = (v[1:-1,2:] - v[1:-1,:-2]) / (xc[np.newaxis,2:] - xc[np.newaxis,:-2])
    
    return dvdx - dudy


def velocity_profile(case : str, x : np.ndarray, vmax : float, 
                     x0 : float ,ss : float, phi : float) -> np.ndarray:
    '''
    @brief compute vertical velocity on the upper wall

    @details compute blowing-sucking vertical velocity profile on the upper wall
    of the domain to create a separation bubble. Two profiles can be generated:
        - Coleman (2018)
            v = -np.sqrt(2)*vmax*x*np.exp(.5-x**2) + phi
        - Abe (2017)
            v = -np.sqrt(2)*vmax*x*np.exp(phi-x**2)

    Usage:
    v = velocity_profile(case,x,vmax,x0,ss,phi):

    @param case     [str] 'coleman' or 'abe'
    @param x        [arr] x-coordinate to compute the velocity
    @param vmax     [dbl] maximum velocity
    @param x0       [dbl] mid position of the blowing-suction profile
    @param ss       [dbl] sigma, defines width of profile
    @param phi      [dbl] offset

    @param v        [arr] vertical velocity computed at x

    '''
    v = np.empty(0) # init v 

    x = (x-x0)/ss # normalize x-coordinate
    if case.lower() == 'coleman':
        v = -np.sqrt(2)*vmax*x*np.exp(.5-x**2) + phi
    elif case.lower() == 'abe':
        v = -np.sqrt(2)*vmax*x*np.exp(phi-x**2)
    else:
        ValueError(
            f'case must be "coleman" or "abe". Currently, \ncase = {case}')

    return v


class ymesh:
    '''
    @brief class to work with the mesh used by BL code in Fortran
    '''
    _nydef = 91 # default number of grid points
    _alp  = 6.2 # grid factor

    def __init__(self, Ly : float, ny : int = _nydef, alp : float= _alp):

        self.Ly = Ly
        self.ny = ny
        self.alp = alp

        self._getmesh()

    def _getmesh(self):
        '''
        @brief compute the y-coordinate of the mesh

        @detail private method to compute the y-coordinates of the mesh knowing
        the number of point (self.ny) and the grid factor (self._alp). Values
        are stored in self.points
        '''
        self.points = np.sinh( self.alp*np.linspace( 0, 1 , self.ny ) 
                              ) / np.sinh( self.alp )*self.Ly

    def getcontrolj(self,yp):
        '''
        @brief return index of the closest grid point given a value

        @detail
            j = self.getcontrolj(yp)

        intput:
            - yp    query point
        output
            - j     index of the closest grid point to yp
        '''
        y = self.points
        return abs(y - yp).argmin()

    def getyfromj(self,j):
        '''
        @brief return the y-coordinate of the mesh given the index

        @detail
            y = self.getyfromj(j)

        intput:
            - j     [single value or list] index
        output
            - y     y-coordiate (same dim as j)
        '''
        return self.points[j]

    def getclosesty(self,y):
        '''
        @brief return the closest y point of the grid given a value

        @detail
            y = self.getclosesty(yp)

        intput:
            @param yp     query y-coordinate
        output
            @param y      closest value of the grid
        '''
        return self.getyfromj(self.getcontrolj(y))

